import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Camera,Mic,Monitor,Radio,Settings,LogOut,MessageSquare,Gift,ArrowRight,ShieldCheck,RefreshCw,Square,Video,VolumeX} from 'lucide-react';
import LiveChatPanel from "../shared/pages/live/LiveChatPanel.jsx";
import LiveCommerceStudio from "../shared/pages/live/LiveCommerceStudio.jsx";
import {invoke} from "./bridge.js";import {setUser} from "./auth.js";import {setSession} from "./adapter.js";
import "./style.css";
import useLivePolling from "../shared/hooks/useLivePolling.js";
const money=value=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format((value||0)/100);
function Revenue({sessionId}){const {data,error}=useLivePolling('/lives/'+sessionId+'/accounting',15000);return <section className="revenue-panel"><h3>Receita desta live</h3>{error?<p role="alert">{error}</p>:data?<><strong>{money(data.received?.net_cents)}</strong><p>{money(data.received?.gross_cents)} recebidos · {money(data.received?.refunded_cents)} devolvidos</p><p className="fine">Resumo da sessão. A comissão continua no saque; este valor não é uma carteira adicional.</p></>:<p>Consultando registros…</p>}</section>}

const statusNames={waiting:'Na fila',reserved:'Vaga disponível',starting:'Conectando',live:'Ao vivo',reconnecting:'Reconectando',ending:'Encerrando'};
const hiddenBounds={x:0,y:0,width:0,height:0};
function previewBounds(element){
  if(!element||document.hidden)return hiddenBounds;
  const obscured=[...document.querySelectorAll('[role="dialog"], [role="alertdialog"], [role="menu"], [role="listbox"], dialog[open], [data-radix-popper-content-wrapper]')].some(node=>node.getClientRects().length&&getComputedStyle(node).visibility!=='hidden'&&node.getAttribute('aria-hidden')!=='true');
  if(obscured)return hiddenBounds;
  const rect=element.getBoundingClientRect();
  if(rect.width<1||rect.height<1||rect.left<0||rect.top<0||rect.right>innerWidth+.5||rect.bottom>innerHeight+.5)return hiddenBounds;
  for(let node=element.parentElement;node&&node!==document.body;node=node.parentElement){
    const style=getComputedStyle(node),clip=node.getBoundingClientRect();
    if(style.display==='none'||style.visibility==='hidden'||Number(style.opacity)===0)return hiddenBounds;
    if(/auto|scroll|hidden|clip/.test(style.overflowY)&& (rect.top<clip.top-.5||rect.bottom>clip.bottom+.5))return hiddenBounds;
    if(/auto|scroll|hidden|clip/.test(style.overflowX)&& (rect.left<clip.left-.5||rect.right>clip.right+.5))return hiddenBounds;
  }
  return{x:rect.x,y:rect.y,width:rect.width,height:rect.height};
}
function UpdateBanner({info,blocked,run}){
  if(!info?.available&&info?.status!=='error')return null;
  const working=['downloading','installing'].includes(info.status);
  return <section className="update-banner" aria-label="Atualização do aplicativo"><div><strong>{info.status==='installing'?'Preparando instalação':info.status==='downloading'?'Baixando atualização':info.status==='error'?'Não foi possível atualizar':'Atualização disponível'}</strong><span>{info.status==='downloading'?`${Math.round(info.progress||0)}% baixado`:blocked?'Encerre sua live para atualizar com segurança.':`Privex Studio ${info.latestVersion||''}`}</span>{working&&<progress aria-label="Progresso da atualização" max="100" value={info.progress||0}/>}</div><button className="secondary" disabled={blocked||working} onClick={()=>run('updates.install')}>{working?'Aguarde…':info.status==='error'?'Tentar novamente':'Atualizar app'}</button></section>;
}
function UpdatePreferences({state,busy,run}){
  return <details className="mt-4 rounded-lg border border-px-border p-3 text-xs text-px-muted"><summary className="cursor-pointer">Privacidade e atualizações</summary><label className="mt-3 flex min-h-11 items-center gap-3"><input type="checkbox" className="h-4 w-4 shrink-0 accent-purple-500" checked={state.automaticUpdateChecks!==false} disabled={busy||typeof state.automaticUpdateChecks!=='boolean'} onChange={event=>run('updates.automatic',{enabled:event.target.checked})}/><span>Consultar atualizações automaticamente</span></label><p className="mt-2 leading-relaxed">Consulta privex.site ao abrir e a cada 6 horas. O servidor recebe seu IP e dados técnicos da conexão. Esta consulta não envia sua conta nem a versão instalada. A instalação depende da sua confirmação.</p><p className="mt-2 leading-relaxed">Ao desativar, novas consultas só acontecem quando você verifica ou instala uma atualização manualmente.</p></details>;
}
function App(){
  const [state,setState]=useState({}),[error,setError]=useState(''),[title,setTitle]=useState(''),[source,setSource]=useState('camera'),[camera,setCamera]=useState(''),[mic,setMic]=useState(''),[screen,setScreen]=useState(''),[portrait,setPortrait]=useState(false),[devices,setDevices]=useState(null),[tab,setTab]=useState('chat'),[muted,setMuted]=useState(false),[localBusy,setLocalBusy]=useState(false);
  const preview=useRef(null);const session=state.studio?.session;const owned=session?.managed_by_device;const displayStatus=session?.status==='live'&&!session.media_ready?'starting':session?.status;const busy=localBusy||state.busy;const sessionActive=!!session&&['waiting','reserved','starting','live','reconnecting','ending'].includes(session.status);const active=owned&&sessionActive;
  const update=value=>{setUser(value.user);setSession(value.studio?.session?.managed_by_device?value.studio.session.id:null);setMuted(!!value.muted);setState(value);};
  useEffect(()=>{invoke('snapshot').then(update);const cleanup=window.privex.onState(update);const timer=setInterval(()=>invoke('snapshot').then(update).catch(()=>{}),5000);return()=>{cleanup();clearInterval(timer);};},[]);
  useLayoutEffect(()=>{
    if(!state.prepared||!preview.current)return;
    let timer,disposed=false,pending=Promise.resolve(),revision=0,lastGeometry='';
    const send=bounds=>{const version=++revision;pending=pending.catch(()=>{}).then(()=>{if(disposed||version!==revision)return;return invoke('bounds',bounds);}).catch(()=>{});};
    const resize=()=>{const bounds=previewBounds(preview.current),geometry=JSON.stringify(bounds);if(geometry===lastGeometry)return;lastGeometry=geometry;clearTimeout(timer);send(hiddenBounds);if(bounds.width)timer=setTimeout(()=>{if(!disposed)send(previewBounds(preview.current));},70);};
    const observer=new ResizeObserver(resize);observer.observe(preview.current);observer.observe(document.documentElement);
    const mutation=new MutationObserver(resize);mutation.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['role','aria-hidden','open','data-state','class','style']});
    window.addEventListener('resize',resize);document.addEventListener('scroll',resize,true);document.addEventListener('visibilitychange',resize);window.visualViewport?.addEventListener('resize',resize);resize();
    return()=>{disposed=true;revision++;clearTimeout(timer);observer.disconnect();mutation.disconnect();window.removeEventListener('resize',resize);document.removeEventListener('scroll',resize,true);document.removeEventListener('visibilitychange',resize);window.visualViewport?.removeEventListener('resize',resize);void invoke('bounds',hiddenBounds).catch(()=>{});};
  },[state.prepared,portrait]);
  async function run(name,data){setError('');setLocalBusy(true);try{return await invoke(name,data);}catch(e){setError(e.message);}finally{setLocalBusy(false);}}
  async function enumerate(){const data=await run('enumerate');if(data){setDevices(data);setCamera('');setMic('');setScreen('');}}
  const options=(items)=>(items||[]).map(item=><option key={item.id??item.value} value={item.id??item.value}>{item.name??item.label}</option>);
  if(!state.user)return <main className="welcome">
    <header className="brand"><span className="brand-mark">p<span>×</span></span> Privex <b>Studio</b><small>BETA</small></header>
    <UpdateBanner info={state.updateInfo} blocked={!!(busy||state.transmitting||sessionActive)} run={run}/>
    <div className="welcome-grid"><section><p className="eyebrow">SEU ESPAÇO PARA TRANSMITIR</p><h1>Sua live.<br/>Do seu jeito.</h1><p className="welcome-copy">Câmera, conversa e interações no mesmo lugar. Entre na sua conta Privex para preparar sua transmissão.</p><div className="feature-row"><span><Camera size={18}/> Câmera e tela</span><span><MessageSquare size={18}/> Chat integrado</span><span><Gift size={18}/> Metas e presentes</span></div></section>
    <section className="login-card"><div className="login-icon"><Radio size={32}/></div><h2>{state.pendingAccount?'Confirme sua conta':'Entrar com Privex'}</h2>
      {state.pendingAccount?<><p>Confira qual conta foi autorizada neste computador. Confirme a conta que você quer usar.</p><div className="pending-account"><strong>{state.pendingAccount.name||state.pendingAccount.username}</strong><span>@{state.pendingAccount.username}</span></div><button className="primary" disabled={busy} onClick={()=>run('account.confirm')}>Continuar como @{state.pendingAccount.username} <ArrowRight size={18}/></button><button className="secondary account-switch" disabled={busy} onClick={()=>run('account.switch')}>Usar outra conta</button></>:<><p>Você confirma a conexão no site oficial. Sua senha fica no Privex.</p>{state.authorization?<><p className="code">{state.authorization.code}</p><p role="status">Confira este código no navegador e autorize este computador.</p><button className="secondary" disabled={busy} onClick={()=>run('login.cancel')}>Cancelar conexão</button></>:<button className="primary" disabled={busy} onClick={()=>run('login')}>Conectar minha conta <ArrowRight size={18}/></button>}</>}
      <p className="fine"><ShieldCheck size={15}/> Para contas ativas e verificadas. Câmera e microfone só são ligados após sua escolha.</p>{(error||state.error)&&<p className="error" role="alert">{error||state.error}</p>}<button className="text-button" onClick={()=>run('terms')}>Termos e condições</button>
      <UpdatePreferences state={state} busy={busy} run={run}/>
    </section></div><footer>Privex Studio {state.version} · Windows · Beta <button className="text-button" disabled={busy} onClick={()=>run('updates.check')}>Verificar atualização</button>{state.notice&&<p role="status">{state.notice}</p>}</footer>
  </main>;
  return <main className="studio"><header className="topbar"><div className="brand"><span className="brand-mark">p<span>×</span></span> Privex <b>Studio</b><small>BETA</small></div><span className={`signal ${displayStatus==='live'?'is-live':''}`}><i/>{statusNames[displayStatus]||'Fora do ar'}</span><div className="account"><button className="text-button" disabled={busy||sessionActive||state.transmitting} onClick={()=>run('updates.check')}>Atualizações</button><span>@{state.user.username}</span><button title="Sair da conta" aria-label="Sair da conta" disabled={busy||active} onClick={()=>run('logout')}><LogOut size={18}/></button></div></header>
    <UpdateBanner info={state.updateInfo} blocked={!!(sessionActive||state.transmitting||busy)} run={run}/>
    <div className="workspace"><section className="production"><div className="section-heading"><div><p className="eyebrow">TRANSMISSÃO</p><h1>{state.transmitting?'Seu sinal está sendo enviado':'Prepare sua live'}</h1></div><span className="format-badge">{portrait?'9:16':'16:9'}</span></div>
      <div className="preview-shell"><div className="preview-stage"><div ref={preview} className={portrait?'preview is-portrait':'preview'}>{!state.prepared&&<div className="preview-empty"><Video size={42}/><h2>Vamos preparar sua câmera?</h2><p>Escolha os equipamentos abaixo.<br/>A prévia aparece aqui antes de você entrar ao vivo.</p></div>}</div></div><div className="preview-caption">{state.transmitting?'Vídeo enviado · confira a confirmação de sinal no topo':'PRÉVIA LOCAL · ainda não é uma transmissão pública'}</div></div>
      <section className="equipment"><div className="section-heading"><h2><Settings size={18}/> Equipamentos</h2><button className="text-button" disabled={busy||state.transmitting} onClick={enumerate}><RefreshCw size={15}/> {devices?'Atualizar lista':'Buscar equipamentos'}</button></div>
      <div className="settings-grid"><label>Fonte<select value={source} disabled={busy||state.transmitting} onChange={e=>{setSource(e.target.value);setScreen('');}}><option value="camera">Câmera</option><option value="window">Uma janela</option><option value="display">Tela inteira</option></select></label>
      <label>{source==='camera'?'Câmera':'O que compartilhar'}<select disabled={busy||state.transmitting||!devices} value={source==='camera'?camera:screen} onChange={e=>source==='camera'?setCamera(e.target.value):setScreen(e.target.value)}><option value="">Escolha explicitamente</option>{options(source==='camera'?devices?.cameras:source==='window'?devices?.windows:devices?.displays)}</select></label>
      <label>Microfone<select disabled={busy||state.transmitting||!devices} value={mic} onChange={e=>setMic(e.target.value)}><option value="">Sem microfone</option>{options(devices?.microphones)}</select></label><label>Formato<select disabled={busy||state.transmitting} value={portrait?'portrait':'landscape'} onChange={e=>setPortrait(e.target.value==='portrait')}><option value="landscape">Horizontal · 16:9</option><option value="portrait">Vertical · 9:16</option></select></label></div>
      {source==='display'&&<p className="warning">Tudo nessa tela pode aparecer, inclusive o gerenciador. Prefira compartilhar uma janela.</p>}
      <div className="equipment-actions"><button className="secondary" disabled={busy||state.transmitting||!(source==='camera'?camera:screen)} onClick={()=>run('prepare',{sourceType:source,cameraId:camera,microphoneId:mic,sourceId:screen,portrait})}><Camera size={17}/>{state.prepared?'Aplicar equipamentos':'Abrir prévia local'}</button><button className={muted?'muted-button':'secondary'} disabled={!state.prepared||busy} onClick={async()=>{const result=await run('mute',{muted:!muted});if(result!==undefined)setMuted(!muted);}}>{muted?<VolumeX size={17}/>:<Mic size={17}/>} {muted?'Microfone silenciado':'Silenciar microfone'}</button><button className="secondary" disabled={!state.prepared||busy} onClick={()=>run('scene',{mode:state.sceneMode==='pause'?'live':'pause'})}>{state.sceneMode==='pause'?'Voltar à câmera':'Cena de intervalo'}</button><label className="fine"><input type="checkbox" checked={!!state.overlayEnabled} disabled={!owned||busy} onChange={e=>run('overlay',{enabled:e.target.checked})}/> Mostrar meta no vídeo</label></div></section>
      <label className="title-field">Título da live<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} disabled={busy||active} placeholder="O que vamos fazer hoje?"/></label>
      {(error||state.error)&&<p role="alert" className="error">{error||state.error}</p>}{state.notice&&<p role="status" className="notice">{state.notice}</p>}
      {session&&!owned&&<p className="warning">Há uma live em outro dispositivo. Gerencie pelo site antes de iniciar aqui.</p>}
      <UpdatePreferences state={state} busy={busy} run={run}/>
    </section><aside className="manager"><div className="manager-heading"><h2>Seu gerenciador</h2><p>Conectado à mesma live do site</p></div><div className="tabbar" role="tablist" aria-label="Gerenciador"><button role="tab" aria-selected={tab==='chat'} onClick={()=>setTab('chat')}><MessageSquare size={17}/> Chat</button><button role="tab" aria-selected={tab==='commerce'} onClick={()=>setTab('commerce')}><Gift size={17}/> Interações</button></div><div className="manager-content" role="tabpanel">{owned?<React.Fragment key={session.id}>{tab==='chat'?<LiveChatPanel sessionId={session.id}/>:<><Revenue sessionId={session.id}/><LiveCommerceStudio sessionId={session.id}/></>}</React.Fragment>:<div className="manager-empty"><MessageSquare size={30}/><h3>Todo mundo por perto</h3><p>Ao abrir uma sessão, seu chat, metas, roleta e presentes estarão aqui.</p><p className="fine">As interações usam as mesmas regras e registros do site.</p></div>}</div></aside></div>
    <footer className="controlbar"><div><span className="signal"><i/>{statusNames[displayStatus]||'Pronta para preparar'}</span><p>{session?.status==='waiting'?`Posição na fila: ${session.queue_position||'consultando'}`:'Privex Studio '+state.version+' · 720p · 30 fps'}</p></div><div className="main-actions"><button className="secondary" onClick={()=>run('site')}><Monitor size={17}/> Abrir site</button>{active?<><button className="danger" disabled={busy} onClick={()=>{if(window.confirm('Encerrar a sessão e interromper o envio de vídeo?'))run('end');}}><Square size={16}/> {session.status==='waiting'?'Sair da fila':'Encerrar live'}</button>{['reserved','reconnecting'].includes(session.status)&&!state.transmitting&&<button className="primary" disabled={busy||!state.prepared} onClick={()=>run('resume')}>Estou pronta · transmitir</button>}</>:<button className="primary" disabled={busy||!state.prepared||!title.trim()||session&&!owned} onClick={()=>run('start',{title})}><Radio size={19}/> Iniciar live</button>}</div></footer>
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
